user www-data;
worker_processes auto;
worker_rlimit_nofile 65535;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
    worker_connections 65535;
    multi_accept on;
    use epoll;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    log_format main '$time_local | '
                    'Client IP: $remote_addr | '
                    'Full Request: $request | '
                    'Status: $status | '
                    'Request Time: $request_time | '
                    'Upstream Response Time: $upstream_response_time | ';

    access_log /var/log/nginx/access.log main;
    sendfile        on;
    tcp_nopush      on;

    server {
        listen 80; # SSL kapandı, sadece port 80 aktif
        server_name canliyayin.guler.com;

        # HLS Video Dağıtım Alanı
        location /hls {
            types {
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
            }
            alias /tmp/hls/; # Root yerine alias kullanarak RAM Disk'e doğrudan bağlanıyoruz
            add_header Cache-Control no-cache;
            add_header 'Access-Control-Allow-Origin' '*' always; # Player erişimi için şart
        }

        # Web Arayüzü (index.html)
        location / {
            root  /var/www/html;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /var/www/html;
        }
    }
}

rtmp {
    server {
        listen 1935;
        chunk_size 4096;

        application hls {
            live on;
            hls on;
            hls_path /tmp/hls/;
            hls_fragment 1s;
            hls_playlist_length 10s;
            hls_cleanup on;
            hls_type live;
            hls_continuous off;
           # allow publish 192.168.47.176;  # Sadece bu IP'den gelen yayını kabul et
           # deny publish all;              # Diğer tüm dünyadan gelen yayınları reddet
            hls_fragment_naming system;
        }
    }
}
